name: SimpleVoiceMechanics
version: '1.0.0'
main: de.tecca.simplevoicemechanics.SimpleVoiceMechanics
api-version: '1.21'
author: Tecca
description: Advanced voice detection mechanics for SimpleVoiceChat
website: https://github.com/yourusername/SimpleVoiceMechanics

# Commands
commands:
  voicelistener:
    description: Main command for SimpleVoiceMechanics administration
    usage: /<command> [reload|toggle|status]
    aliases: [vl, voicemechanics]
    permission: voicelistener.admin

# Permissions
permissions:
  voicelistener.*:
    description: Grants all SimpleVoiceMechanics permissions
    default: op
    children:
      voicelistener.admin: true

  voicelistener.admin:
    description: Allows use of all admin commands
    default: op